// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tensu.Api.Data;

#nullable disable

namespace Tensu.Api.Data.Migrations
{
    [DbContext(typeof(TensuDbContext))]
    [Migration("20260707153429_AddDailyStatsAdminAuditWebhooks")]
    partial class AddDailyStatsAdminAuditWebhooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Tensu.Core.Entities.AdminAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("admin_audit_logs", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AllowedModels")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_models");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpWhitelist")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_whitelist");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_prefix");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organization_id");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rate_limit_rpm");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rate_limit_tpm");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.ArchivedRequestLog", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("api_key_id");

                    b.Property<bool>("CacheHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_hit");

                    b.Property<bool>("CompressionApplied")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compression_applied");

                    b.Property<string>("CompressionMappingKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("compression_mapping_key");

                    b.Property<string>("CompressionStrategy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("compression_strategy");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<decimal?>("InputCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("input_cost");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("InputTokensAfterCompression")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens_after_compression");

                    b.Property<bool>("IsStream")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_stream");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organization_id");

                    b.Property<decimal?>("OutputCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_cost");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<double?>("OutputTokensPerSecond")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("output_tokens_per_second");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("RequestContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_content");

                    b.Property<string>("ResolvedModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_model_name");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_content");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<bool>("SemanticCacheHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("semantic_cache_hit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long?>("TimeToFirstTokenMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_to_first_token_ms");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<long?>("TotalDurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_duration_ms");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("RequestId");

                    b.HasIndex("ModelName");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.ToTable("archived_request_logs", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.CompressionMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CompressedBody")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compressed_body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DecompressionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("decompression_key");

                    b.Property<string>("OriginalBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("original_body");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy");

                    b.HasKey("Id");

                    b.HasIndex("DecompressionKey")
                        .IsUnique();

                    b.ToTable("compression_mappings", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.DailyStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("AvgLatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("avg_latency_ms");

                    b.Property<double?>("AvgOutputTokensPerSecond")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("avg_output_tokens_per_second");

                    b.Property<long?>("AvgTtftMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("avg_ttft_ms");

                    b.Property<int>("CacheHits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_hits");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("FailedRequests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_requests");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organization_id");

                    b.Property<long?>("P50LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("p50_latency_ms");

                    b.Property<long?>("P95LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("p95_latency_ms");

                    b.Property<long?>("P99LatencyMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("p99_latency_ms");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<int>("RateLimitedRequests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rate_limited_requests");

                    b.Property<int>("SuccessRequests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success_requests");

                    b.Property<decimal>("TotalInputCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_input_cost");

                    b.Property<long>("TotalInputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_input_tokens");

                    b.Property<long>("TotalInputTokensAfterCompression")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_input_tokens_after_compression");

                    b.Property<decimal>("TotalOutputCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("total_output_cost");

                    b.Property<long>("TotalOutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_output_tokens");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_requests");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Date", "OrganizationId", "ModelName", "ProviderName")
                        .IsUnique();

                    b.ToTable("daily_stats", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.DataDeletionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("api_key_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DeletedArchivedLogs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_archived_logs");

                    b.Property<int>("DeletedRequestLogs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted_request_logs");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("data_deletion_requests", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("CompressionEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compression_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int>("InputContextSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_context_size");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("OutputContextSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_context_size");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_id");

                    b.Property<bool>("SupportsReasoning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_reasoning");

                    b.Property<bool>("SupportsThinking")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_thinking");

                    b.Property<bool>("SupportsToolUse")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_tool_use");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("supports_vision");

                    b.Property<string>("ThinkingStrengths")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("thinking_strengths");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "Name")
                        .IsUnique();

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.ModelCapability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("dimension");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("Evidence")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<decimal>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ModelId", "Dimension")
                        .IsUnique();

                    b.ToTable("model_capabilities", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.ModelPricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal?>("CachedInputPricePerMillionTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("cached_input_price_per_million");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_to");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("exchange_rate");

                    b.Property<decimal>("InputPricePerMillionTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("input_price_per_million");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<decimal>("OutputPricePerMillionTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_price_per_million");

                    b.Property<decimal?>("ThinkingPricePerMillionTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("thinking_price_per_million");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("model_pricings", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.OAuthProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthorizationEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("authorization_endpoint");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_secret");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Issuer")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("issuer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("TokenEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("token_endpoint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserInfoEndpoint")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("userinfo_endpoint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("oauth_providers", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("CompressionEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compression_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DataRetentionDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_retention_days");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("EnableContentLogging")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable_content_logging");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("base_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("health_status");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("KeyLoadBalanceStrategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_load_balance_strategy");

                    b.Property<DateTime?>("LastHealthCheckAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_health_check_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.ProviderKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_value");

                    b.Property<DateTime?>("LastHealthCheckAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_health_check_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_id");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rate_limit_rpm");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rate_limit_tpm");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("provider_keys", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.Quota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("api_key_id");

                    b.Property<int?>("ConcurrentRequestLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("concurrent_request_limit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long?>("DailyTokenLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("daily_token_limit");

                    b.Property<long?>("MonthlyTokenLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("monthly_token_limit");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organization_id");

                    b.Property<int?>("Rpm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rpm");

                    b.Property<int?>("Tpm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tpm");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("quotas", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.RateLimitCounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.Property<int>("WindowSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("window_seconds");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "WindowStart")
                        .IsUnique();

                    b.HasIndex("Scope", "WindowStart", "WindowSeconds");

                    b.ToTable("rate_limit_counters", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.RequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("api_key_id");

                    b.Property<bool>("CacheHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_hit");

                    b.Property<bool>("CompressionApplied")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compression_applied");

                    b.Property<string>("CompressionMappingKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("compression_mapping_key");

                    b.Property<string>("CompressionStrategy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("compression_strategy");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<decimal?>("InputCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("input_cost");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("InputTokensAfterCompression")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens_after_compression");

                    b.Property<bool>("IsStream")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_stream");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organization_id");

                    b.Property<decimal?>("OutputCost")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_cost");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<double?>("OutputTokensPerSecond")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("output_tokens_per_second");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<string>("RequestContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_content");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("ResolvedModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_model_name");

                    b.Property<string>("ResponseContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("response_content");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<bool>("SemanticCacheHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("semantic_cache_hit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long?>("TimeToFirstTokenMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time_to_first_token_ms");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<long?>("TotalDurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_duration_ms");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ModelName");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.ToTable("request_logs", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.RouteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("FallbackModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fallback_model_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("RoutingModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("routing_model_id");

                    b.Property<int?>("TargetModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_model_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FallbackModelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RoutingModelId");

                    b.HasIndex("TargetModelId");

                    b.ToTable("route_models", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.RouteRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<int>("RouteModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("route_model_id");

                    b.Property<int>("TargetModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_model_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RouteModelId");

                    b.HasIndex("TargetModelId");

                    b.ToTable("route_rules", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.SemanticCacheEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("embedding");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsStream")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_stream");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_body");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("response_body");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Model");

                    b.ToTable("semantic_cache_entries", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("picture_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.WebhookNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("events");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Secret")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("webhook_notifications", (string)null);
                });

            modelBuilder.Entity("Tensu.Core.Entities.ApiKey", b =>
                {
                    b.HasOne("Tensu.Core.Entities.Organization", "Organization")
                        .WithMany("ApiKeys")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tensu.Core.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tensu.Core.Entities.Model", b =>
                {
                    b.HasOne("Tensu.Core.Entities.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Tensu.Core.Entities.ModelCapability", b =>
                {
                    b.HasOne("Tensu.Core.Entities.Model", "Model")
                        .WithMany("Capabilities")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Tensu.Core.Entities.ModelPricing", b =>
                {
                    b.HasOne("Tensu.Core.Entities.Model", "Model")
                        .WithMany("Pricings")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Tensu.Core.Entities.Organization", b =>
                {
                    b.HasOne("Tensu.Core.Entities.Organization", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Tensu.Core.Entities.ProviderKey", b =>
                {
                    b.HasOne("Tensu.Core.Entities.Provider", "Provider")
                        .WithMany("Keys")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Tensu.Core.Entities.Quota", b =>
                {
                    b.HasOne("Tensu.Core.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tensu.Core.Entities.Organization", "Organization")
                        .WithMany("Quotas")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tensu.Core.Entities.RouteModel", b =>
                {
                    b.HasOne("Tensu.Core.Entities.Model", "FallbackModel")
                        .WithMany()
                        .HasForeignKey("FallbackModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tensu.Core.Entities.Model", "RoutingModel")
                        .WithMany()
                        .HasForeignKey("RoutingModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tensu.Core.Entities.Model", "TargetModel")
                        .WithMany()
                        .HasForeignKey("TargetModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FallbackModel");

                    b.Navigation("RoutingModel");

                    b.Navigation("TargetModel");
                });

            modelBuilder.Entity("Tensu.Core.Entities.RouteRule", b =>
                {
                    b.HasOne("Tensu.Core.Entities.RouteModel", "RouteModel")
                        .WithMany("Rules")
                        .HasForeignKey("RouteModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tensu.Core.Entities.Model", "TargetModel")
                        .WithMany()
                        .HasForeignKey("TargetModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteModel");

                    b.Navigation("TargetModel");
                });

            modelBuilder.Entity("Tensu.Core.Entities.User", b =>
                {
                    b.HasOne("Tensu.Core.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Tensu.Core.Entities.Model", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("Pricings");
                });

            modelBuilder.Entity("Tensu.Core.Entities.Organization", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Children");

                    b.Navigation("Quotas");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Tensu.Core.Entities.Provider", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("Tensu.Core.Entities.RouteModel", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Tensu.Core.Entities.User", b =>
                {
                    b.Navigation("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
